# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba09974a98e186ae4ac476c48921a14c659c93c3d61c295458f043f283c461d75172de5abaa7fe7db33ddbb85897b70446a60e29a33566884d99de2cb60cfdde

test:
  secret_key_base: 0d22dab6500529c70090467e4ed0801c1512506d77ae06cc863b6ae92b06b145111c68aa609f2535321091acabb42538a94c46c3e14b43c295ee7db06a3c7bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
